-- MySQL Script generated by MySQL Workbench
-- sáb 11 jul 2020 16:57:30 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema olhoVivo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema olhoVivo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `olhoVivo` DEFAULT CHARACTER SET utf8 ;
USE `olhoVivo` ;

-- -----------------------------------------------------
-- Table `olhoVivo`.`Parada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhoVivo`.`Parada` (
  `parada_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `parada_name` TINYTEXT NOT NULL,
  `parada_latitude` DOUBLE NOT NULL,
  `parada_longitude` DOUBLE NOT NULL,
  PRIMARY KEY (`parada_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhoVivo`.`Linha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhoVivo`.`Linha` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhoVivo`.`Relaciona_Linha_Parada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhoVivo`.`Relaciona_Linha_Parada` (
  `linha_id` INT UNSIGNED NOT NULL,
  `parada_id` INT UNSIGNED NOT NULL,
  INDEX `fk_Relaciona_Linha_parada_1_idx` (`linha_id` ASC),
  INDEX `fk_Relaciona_Linha_parada_2_idx` (`parada_id` ASC),
  CONSTRAINT `fk_Relaciona_Linha_parada_1`
    FOREIGN KEY (`linha_id`)
    REFERENCES `olhoVivo`.`Linha` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Relaciona_Linha_parada_2`
    FOREIGN KEY (`parada_id`)
    REFERENCES `olhoVivo`.`Parada` (`parada_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhoVivo`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhoVivo`.`Veiculo` (
  `veiculo_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `linha_id` INT UNSIGNED NOT NULL,
  `veiculo_name` TINYTEXT NOT NULL,
  `veiculo_modelo` TINYTEXT NOT NULL,
  PRIMARY KEY (`veiculo_id`),
  INDEX `fk_Veiculo_1_idx` (`linha_id` ASC),
  CONSTRAINT `fk_Veiculo_1`
    FOREIGN KEY (`linha_id`)
    REFERENCES `olhoVivo`.`Linha` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olhoVivo`.`Posicao_Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olhoVivo`.`Posicao_Veiculo` (
  `veiculo_id` INT UNSIGNED NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `logitude` DOUBLE NOT NULL,
  PRIMARY KEY (`veiculo_id`),
  CONSTRAINT `fk_Posicao_Veiculo_1`
    FOREIGN KEY (`veiculo_id`)
    REFERENCES `olhoVivo`.`Veiculo` (`veiculo_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
